### ISSUE TITLE
License is not clear BSD-3

### ISSUE THREAD

**Issue by luc1dm0nk3y** [ixe013/notifu#2]
Looks like the license this package is issued under is not registering as a standard BSD-3, did you make any modifications to the BSD-3 license?

**Comment by ixe013** [comment]
I did not make any change - not intentionally anyway... I did move the code from my personnal Subversion to this Github repo though. I added the BSD license in every source file and binary starting at version 1.7. Before that, it was just mentionned on the website for the project.

When you say the project is...

> not registering as a standard BSD-3

I beleive you mean that Github does not display it? I'll add a `LICENCE` file, should fix it.

**Comment by ixe013** [comment]
The license shows not that I've pushed https://github.com/ixe013/notifu/commit/159b3b238bed15e1830dc41a01efd41dfca6572a (straight to `master`, my bad). 

Does it solve the issue for you, @luc1dm0nk3y ?
