### ISSUE TITLE
/d Does Not Work On Windows 11

### ISSUE THREAD

**Issue by war59312** [ixe013/notifu#5]
/d Does Not Work On Windows 11

The pop-up goes away after a few seconds no matter what.

Edit: Known issue but here in case someone runs into it.

`Modern Windows version will dismiss the pop-up before the timeout expires.`

**Comment by ixe013** [comment]
Works as (Microsoft) intended. Notifu calls the Windows API that utimately decides how long the message is displayed.

Windows will honor the timeout if your mouse hovers the message.
