### ISSUE TITLE
Mark Project As Archived

### ISSUE THREAD

**Issue by war59312** [ixe013/notifu#6]
Suggest marking this project As Archived

Settings > Danger Zone > Archive this repository

Since clearly no longer supported.

**Comment by ixe013** [comment]
What makes you think that it's not supported anymore?

**Comment by war59312** [comment]
Generally with no code in 4 years, means not supported but happy to hear if you still are. :)

**Comment by ixe013** [comment]
Wow, 4 years already. Time flies! And that was when I moved the code from my trusty old, self-hosted Subversion.
